std = "lua51"
max_line_length = false
exclude_files = {
	"**/Libs/**/*.lua",
	".luacheckrc",
}
ignore = {
	"11./SLASH_.*", -- Setting an undefined (Slash handler) global variable
	"11./BINDING_.*", -- Setting an undefined (Keybinding header) global variable
	"212/self", -- Unused argument 'self'
}
globals = {
	-- Saved Variables
	"Prat3DB",
	"Prat3CharDB",
	"Prat3HighCPUPerCharDB",

	-- Prat
	"Prat",
	"Prat_PopupFrame",
	"Prat_PopupFrameText",
	"Prat_ToggleOptionsWindow",
	"PratCCFrame",
	"PratCCFrameScrollText",
	"PratCCFrameScrollScrollBar",
	"PratCCText",
	"CHAT_SMARTGROUP_SEND",
	"CHAT_SMARTGROUP_GET",

	-- Libraries
	"AceGUIWidgetLSMlists",
	"GLDG_Data",
	"LibStub",
	"LOKWhoIsWho_Config",
	"WIM",

	-- Utility functions
	"date",
	"difftime",
	"geterrorhandler",
	"strcmputf8i",
	"strsplit",
	"time",
	"table.wipe",
	-- DEPRECATIONS
	"floor", -- math.floor
	--
	"format", -- string.format
	"strlen", -- string.len
	"strmatch", -- string.match
	"strsub", -- string.sub
	"strlower", -- string.lower
	"strupper", -- string.upper
	"strfind", -- string.find
	--
	"tinsert", -- table.insert
	"tremove", -- table.remove
	"wipe", -- table.wipe

	-- Global constants
	"AUTOCOMPLETE_LIST_TEMPLATES",
	"CHAT_FRAMES",
	"CHAT_FRAME_BUTTON_FRAME_MIN_ALPHA",
	"CHAT_FRAME_TAB_NORMAL_NOMOUSE_ALPHA",
	"CHAT_FRAME_TAB_SELECTED_NOMOUSE_ALPHA",
	"CHAT_FRAME_TEXTURES",
	"CUSTOM_CLASS_COLORS",
	"DEFAULT_CHAT_FRAME",
	"GENERAL_CHAT_DOCK",
	"DEFAULT_CHATFRAME_ALPHA",
	"GROUP_TAG_LIST",
	"ICON_LIST",
	"ICON_TAG_LIST",
	"LE_PARTY_CATEGORY_INSTANCE",
	"LE_REALM_RELATION_SAME",
	"MAX_WOW_CHAT_CHANNELS",
	"NUM_CHAT_WINDOWS",
	"RAID_CLASS_COLORS",
	"SELECTED_CHAT_FRAME",
	"SOUNDKIT",
	"WOW_PROJECT_CLASSIC",
	"WOW_PROJECT_ID",
	"WOW_PROJECT_MAINLINE",
	"WOW_PROJECT_MISTS_CLASSIC",

	-- Global Strings
	"ACCEPT",
	"BN_INLINE_TOAST_BROADCAST",
	"BN_INLINE_TOAST_BROADCAST_INFORM",
	"CANCEL",
	"CHANNEL",
	"CHAT_BN_CONVERSATION_SEND",
	"CHAT_IGNORED",
	"CHAT_FILTERED",
	"CHAT_FLAG_AFK",
	"CHAT_FLAG_DND",
	"CHAT_MSG_BN_WHISPER_INFORM",
	"CHAT_MSG_CHANNEL_LIST",
	"CHAT_MSG_INSTANCE_CHAT",
	"CHAT_MSG_INSTANCE_CHAT_LEADER",
	"CHAT_MSG_SAY",
	"CHAT_MSG_WHISPER_INFORM",
	"CHAT_RESTRICTED_TRIAL",
	"CHAT_TRIAL_RESTRICTED_NOTICE_TRIAL",
	"ICON_TAG_RAID_TARGET_STAR1",
	"ICON_TAG_RAID_TARGET_STAR12",
	"INSTANCE_CHAT_MESSAGE",
	"INSTANCE_CHAT_LEADER",
	"NPEV2_CHAT_USER_TAG_GUIDE",
	"NPEV2_CHAT_USER_TAG_NEWCOMER",
	"PLAYER_LIST_DELIMITER",
	"TIME_DAYHOURMINUTESECOND",
	"UNKNOWN",

	-- Misc
	"BackdropTemplateMixin",
	"BattlePetTooltip",
	"BattlePetToolTip_ShowLink",
	"ChatFrame1EditBox",
	"ChatFrame1",
	"ChatFrame2",
	"ChatFrame3",
	"ChatFrame4",
	"ChatFrame5",
	"ChatFrame6",
	"ChatFrame7",
	"ChatFrame8",
	"ChatFrame9",
	"ChatFrame10",
	"ChatFrameChannelButton",
	"ChatFrameMenuButton",
	"ChatFrameToggleVoiceDeafenButton",
	"ChatFrameToggleVoiceMuteButton",
	"ChatTypeGroup",
	"ChatTypeInfo",
	"CopyTable",
	"DevTools_Dump",
	"EventRegistry.RegisterCallback",
	"EventRegistry.UnregisterCallback",
	"FCF_Close",
	"FCF_DockUpdate",
	"FCF_FadeInChatFrame",
	"FCF_GetChatWindowInfo",
	"FCF_GetCurrentChatFrame",
	"FCF_IsValidChatFrame",
	"FCF_MaximizeFrame",
	"FCF_MinimizeFrame",
	"FCF_SetChatWindowFontSize",
	"FCF_SelectDockFrame",
	"FCF_SetWindowName",
	"FCF_StartAlertFlash",
	"FCF_StopAlertFlash",
	"FCFDock_GetChatFrames",
	"FCFDock_GetSelectedWindow",
	"FCFDock_SelectWindow",
	"FCFManager_ShouldSuppressMessage",
	"FCFManager_ShouldSuppressMessageFlash",
	"FCFTab_UpdateAlpha",
	"FriendsMicroButton",
	"FloatingChatFrame_Update",
	"GameFontNormal",
	"GameTooltip",
	"GMChatFrame_IsGM",
	"ItemRefTooltip",
	"Mixin",
	"PlayerLocation.CreateFromGUID",
	"QuickJoinToastButton",
	"SlashCmdList",
	"StaticPopupDialogs",
	"StaticPopup_Show",
	"TooltipDataProcessor.AddTooltipPostCall",
	"UIFrameFadeOut",
	"UIFrameFadeRemoveFrame",
	"UIParent",
	"UIParentLoadAddOn",

	-- Enums
	"Constants.ChatFrameConstants.MaxChatChannels",
	"Constants.ChatFrameConstants.MaxChatWindows",
	"ChatFrameConstants.TruncatedCommunityNameLength",
	"ChatFrameConstants.TruncatedCommunityNameWithoutChannelLength",
	"ChatFrameConstants.WhisperSoundAlertCooldown",
	"Enum.ChatChannelRuleset.Mentor",
	"Enum.ClubStreamType.General",
	"Enum.ClubStreamType.Guild",
	"Enum.ClubStreamType.Officer",
	"Enum.ItemClass.Armor",
	"Enum.ItemClass.Profession",
	"Enum.ItemClass.Weapon",
	"Enum.PlayerMentorshipStatus.Mentor",
	"Enum.PlayerMentorshipStatus.Newcomer",
	"Enum.TooltipDataType.Unit",

	-- Utils
	"Chat_GetChatCategory",
	"Chat_GetChatFrame",
	"ChatEdit_ChooseBoxForSend",
	"ChatEdit_DeactivateChat",
	"ChatEdit_GetActiveWindow",
	"ChatEdit_OnEscapePressed",
	"ChatFrame_AddMessageGroup",
	"ChatFrame_GetMentorChannelStatus",
	"ChatFrame_GetMessageEventFilters",
	"ChatFrame_GetMobileEmbeddedTexture",
	"ChatFrame_MessageEventHandler",
	"ChatFrame_ReceiveAllPrivateMessages",
	"ChatFrame_RemoveAllChannels",
	"ChatFrame_RemoveAllMessageGroups",
	"ChatFrame_AddCommunitiesChannel",
	"ChatHistory_GetAccessID",
	--
	"ChatFrameMixin.AddMessageGroup",
	"ChatFrameMixin.MessageEventHandler",
	"ChatFrameMixin.ReceiveAllPrivateMessages",
	"ChatFrameMixin.RemoveAllChannels",
	"ChatFrameMixin.RemoveAllMessageGroups",
	--
	"ChatFrameUtil.AddCommunitiesChannel",
	"ChatFrameUtil.CanChatGroupPerformExpressionExpansion",
	"ChatFrameUtil.DeactivateChat",
	"ChatFrameUtil.FlashTabIfNotShown",
	"ChatFrameUtil.GetChatCategory",
	"ChatFrameUtil.GetChatFrame",
	"ChatFrameUtil.GetMentorChannelStatus",
	"ChatFrameUtil.GetOutMessageFormatKey",
	"ChatFrameUtil.GetMobileEmbeddedTexture",
	"ChatFrameUtil.GetPFlag",
	"ChatFrameUtil.ProcessMessageEventFilters",
	"ChatFrameUtil.ProcessSenderNameFilters",
	"ChatFrameUtil.TruncateToMaxLength",
	--
	"TimerunningUtil.AddSmallIcon",

	-- Lua API
	"C_AddOns.IsAddOnLoaded",
	"C_AddOns.GetAddOnInfo",
	"C_AddOns.LoadAddOn",
	"C_BattleNet.GetAccountInfoByID",
	"C_BattleNet.GetFriendAccountInfo",
	"C_ChatBubbles.GetAllChatBubbles",
	"C_ChatInfo.GetChannelRulesetForChannelID",
	"C_ChatInfo.IsChatLineCensored",
	"C_ChatInfo.InChatMessagingLockdown",
	"C_ChatInfo.IsTimerunningPlayer",
	"C_ChatInfo.ReplaceIconAndGroupExpressions",
	"C_ChatInfo.SwapChatChannelsByChannelIndex",
	"C_ClassColor.GetClassColor",
	"C_Club.GetClubInfo",
	"C_Club.GetInfoFromLastCommunityChatLine",
	"C_Club.GetStreamInfo",
	"C_CreatureInfo.GetRaceInfo",
	"C_EncodingUtil.DecodeBase64",
	"C_EncodingUtil.DeserializeCBOR",
	"C_EncodingUtil.EncodeBase64",
	"C_EncodingUtil.SerializeCBOR",
	"C_FriendList.GetFriendInfoByIndex",
	"C_FriendList.GetNumFriends",
	"C_FriendList.GetNumWhoResults",
	"C_FriendList.GetWhoInfo",
	"C_GuildInfo.GuildRoster",
	"C_Item.GetDetailedItemLevelInfo",
	"C_Item.GetItemInfoInstant",
	"C_Map.GetBestMapForUnit",
	"C_Map.GetPlayerMapPosition",
	"C_PlayerInfo.GetClass",
	"C_PlayerInfo.GetRace",
	"C_PlayerMentorship.IsActivePlayerConsideredNewcomer",
	"C_Spell.GetSpellInfo",
	"C_Spell.GetSpellName",
	"C_StringUtil.EscapeLuaFormatString",
	"C_StringUtil.RemoveContiguousSpaces",
	"C_Texture.GetTitleIconTexture",
	"C_Timer.NewTimer",
	"C_VoiceChat.IsLoggedIn",
	"hooksecurefunc",
	"issecretvalue",
	"issecurevariable",
	"Ambiguate",
	"BNGetFriendInfo",
	"BNGetFriendInfoByID",
	"BNGetGameAccountInfo",
	"BNGetNumFriends",
	"ChangeChatColor",
	"CreateAtlasMarkup",
	"CreateColor",
	"CreateFrame",
	"CreateTextureMarkup",
	"EnumerateServerChannels",
	"FlashClientIcon",
	"FormatPercentage",
	"FormatShortDate",
	"GetAchievementInfo",
	"GetAverageItemLevel",
	"GetBattlefieldScore",
	"GetChannelList",
	"GetChannelName",
	"GetChatWindowChannels",
	"GetChatWindowInfo",
	"GetChatWindowMessages",
	"GetChatWindowSavedDimensions",
	"GetChatWindowSavedPosition",
	"GetClassAtlas",
	"GetCVarBool",
	"GetDefaultLanguage",
	"GetDifficultyColor",
	"GetGuildInfo",
	"GetGuildRosterInfo",
	"GetLocale",
	"GetMessageTypeColor",
	"GetMinimapZoneText",
	"GetNumBattlefieldScores",
	"GetNumGroupMembers",
	"GetNumGuildMembers",
	"GetNumSubgroupMembers",
	"GetPlayerInfoByGUID",
	"GetQuestDifficultyColor",
	"GetRaidRosterInfo",
	"GetRaidTargetIndex",
	"GetRealmName",
	"GetRealZoneText",
	"GetServerTime",
	"GetSpellInfo",
	"GetTime",
	"GetUnitName",
	"InCombatLockdown",
	"IsActivePlayerGuide",
	"IsAddOnLoaded", -- Deprecated
	"IsAltKeyDown",
	"IsCombatLog",
	"IsControlKeyDown",
	"IsInGroup",
	"IsInGuild",
	"IsInInstance",
	"IsInRaid",
	"IsSecureCmd",
	"IsShiftKeyDown",
	"JoinChannelByName",
	"JoinTemporaryChannel",
	"LeaveChannelByName",
	"LoggingChat",
	"LoggingCombat",
	"PlaySound",
	"PlaySoundFile",
	"ReloadUI",
	"SafePack",
	"SendChatMessage",
	"SetChatWindowAlpha",
	"SetChatWindowColor",
	"SetChatWindowDocked",
	"SetChatWindowLocked",
	"SetChatWindowName",
	"SetChatWindowSavedDimensions",
	"SetChatWindowSavedPosition",
	"SetChatWindowShown",
	"SetChatWindowSize",
	"SetChatWindowUninteractable",
	"SetCVar",
	"SwapChatChannelByLocalID",
	"UnitClass",
	"UnitCreatureFamily",
	"UnitCreatureType",
	"UnitExists",
	"UnitGUID",
	"UnitHealth",
	"UnitHealthMax",
	"UnitIsFriend",
	"UnitIsPlayer",
	"UnitLevel",
	"UnitName",
	"UnitPower",
	"UnitPowerMax",
	"UnitRace",
	"UnitRealmRelationship",
	"UnitSex",
	"UnitTokenFromGUID",
}
